imports:
    - { resource: config_dev.yml }

parameters:
    app.game.dictionaries:
        - %kernel.project_dir%/app/Resources/data/test.txt

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
