#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    defaults:
        _controller: 'FrameworkBundle:Redirect:redirect'
        route: app_main_index

app:
    resource: '../src/Controller/'
    type: annotation
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: en|fr
